spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.140:3306/graduation_design
    username: root
    password: 159357
  security:
    jwt:
      key: abc1234
      expire-time: 5
  data:
    redis:
      url: redis://159357@192.168.100.140:6379
      host: 6379
      username: root
      password: 159357
mybatis-plus:
  type-aliases-package: com.sapiece.entity.dto
  mapper-locations: classpath:mybatis-plus/mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    com.sapiece: TRACE
  file:
    name: D:/idea/GraduationDesign/app.log
