spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.140:3306/graduation_design
    username: root
    password: 159357
  security:
    jwt:
      key: abc1234
      expire-time: 5
  data:
    redis:
      url: redis://159357@192.168.100.140:6379
      host: 6379
      username: root
      password: 159357