spring:
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 50
      block: 30
  mail:
    host: smtp.163.com
    username: 17685219818@163.com
    password: MLIYLUDOXPUILIFU
  rabbitmq:
    addresses: 192.168.100.129
    username: admin
    password: 123
    virtual-host: /
    port: 5672

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.129:3306/graduation_design
    username: root
    password: SAPiece@zll9
  security:
    jwt:
      key: abc1234
      expire-time: 5
  data:
    redis:
      url: redis://159357@192.168.100.129:6379
      host: 6379
      username: root
      password: 1379qazzll
mybatis-plus:
  type-aliases-package: com.sapiece.entity.dto
  mapper-locations: classpath:mybatis-plus/mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    com.sapiece: TRACE
  file:
    name: D:/idea/GraduationDesign/app.log
springdoc:
  paths-to-match: /api/**
  swagger-ui:
    operations-sorter: alpha